### ISSUE TITLE
Selecting ROWID crashes in 4.7.3

### ISSUE THREAD

**Issue by AidyCC** [vrogier/ocilib#285] opened 2021-10-05 19:55 UTC
Hello

I've hit an issue on MacOS, using ocilib in OCI_WIDE_CHAR mode.  I'm using Oracle Instant Client 19c.

Using this example as the base:-
[ocilib_cpp_api_demo_list_application](https://vrogier.github.io/ocilib/doc/html/group___ocilib_cpp_api_demo_list_application.html)
Modify the query to just select the rowid from the table.  Comment out or modify the code in the loop to only output the first column.

Build & Run the app and I get an AV on this line in resultset.c:-
 OCIRowidToChar(rowid, NULL, &rowid_length, def->rs->stmt->con->err);

Or, if you commented out the line in the loop, this line in memory.c:-
 ret = OCIArrayDescriptorFree(descp, type);

Do you see the same issue?

I can work round the issue by selecting ROWIDTOCHAR(ROWID), but I thought I'd raise it as some of your other samples only select the ROWID so I figured that was how it was designed to work.

Thanks.

**Comment by cjbj** [comment] 2021-10-05 22:05
When I hear of a ROWID crash, the first thing I think of is to set the environment variable ORA_OCI_NO_OPTIMIZED_FETCH to 1. See https://github.com/oracle/python-cx_Oracle/issues/145. This bug is fixed in Oracle 21.1

**Comment by vrogier** [comment] 2021-10-06 13:09
Hi,

Can you provide DD/DML and sample code for it ?

I cannot reproduce it on Windows (19c client) nor Linux (19c client) with a Oracle 19c server (on Windows).

Following code executes ok (on windows and linux) with OCI_CHARSET_WIDE

```sql
create table table_test (value int);
insert into table table_tst values (1);
...
insert into table table_tst values (x);
```

```c
int main()
{
    OCI_Initialize(err_handler, NULL, OCI_ENV_DEFAULT);

    OCI_Connection* conn = OCI_ConnectionCreate(OTEXT("localhost:1521/db19c"), OTEXT("usr"), OTEXT("pwd"), OCI_SESSION_DEFAULT);
    OCI_Statement* stmt = OCI_StatementCreate(conn);

    OCI_ExecuteStmt(stmt, OTEXT("select rowid from table_test"));
    OCI_Resultset *rs = OCI_GetResultset(stmt);
    while (OCI_FetchNext(rs))
    {
        printf("%ls\n", OCI_GetString(rs, 1));
    }

    printf("row fetched %d\n", OCI_GetRowCount(rs));

    OCI_Cleanup();
}
```
Regards,

Vincent

**Comment by vrogier** [comment] 2021-10-08 16:11
Hi,

thus, on your environment, the following crashes whatever the variable ORA_OCI_NO_OPTIMIZED_FETCH   is set  (I was not aware of this varialbe until Chris mentionned it) ?

OCIRowidToChar(rowid, NULL, &rowid_length, def->rs->stmt->con->err);

If so, there only 4 parameters passed to the function:
- OCIRowid handle retrieved from Oracle Client
- Buffer to receive the string buffer
- Buffer size pointer
- OCI error handle

OCIError handle is used on almost all Oracle client calls thus it is valid
OCIRowid handle is retrieved from Oracle client
Buffer size pointer is correctly initialized

- either the OCIRowidToChar method is NULL (if dynamically loaded) - But when building OCILIB on non windows platforms uses by default static linking rather dynamic loading. Thus I discard this possibility
- either the macOS implementation does not like having a NULL buffer to query the size. Can you try adding a valid local buffer instead of NULL, recompile/install OCILIB ?
- either the macOS implementation is broken for this method.

And btw, do you have the issue when you install OCILIB using default charset (ansi) ?

**Comment by AidyCC** [comment] 2021-10-09 13:12
Yep, here you go (this is still with OCI_CHARSET_ANSI defined) :-
<img width="1240" alt="Screenshot 2021-10-09 at 14 10 27" src="https://user-images.githubusercontent.com/74263551/136659136-f092359a-3c82-489f-8fbb-dcb16b91700d.png">
-

**Comment by vrogier** [comment] 2021-10-10 09:12
One last test you can do, it is to provide a valid local buffer, let's say a unsigned char buffer[100], go the first call to the function instead of passing NULL.
I would be interested to see if it was the reason of the access violation.

Vincent

**Comment by AidyCC** [comment] 2021-10-11 08:34
Vincent,

I had already tried passing a OraText[19] buffer and saw the same issue, but I did try your suggestion:-

<img width="1222" alt="Screenshot 2021-10-11 at 09 28 44" src="https://user-images.githubusercontent.com/74263551/136758164-1a659e2c-e9d1-4ca5-8895-4f2b19576c70.png">

Results are the same.

Full code is below:-

`//
//  main.cpp

// The Instant client libraries must be signed to prevent access errors when running.
// OCI_CHARSET_WIDE must be defined
//
// Expected Result: Resultset.c fails with a AV at line 1801 (OCIRowidToChar(rowid, NULL, &rowid_length, def->rs->stmt->con->err)
//

#include <iostream>
#include "ocilib.h"

void err_handler(OCI_Error *err)
{
    printf("%ls (%d:%d)\n", OCI_ErrorGetString(err), OCI_ErrorGetType(err), OCI_ErrorGetOCICode(err));
}

void vincent_test() {
        OCI_Initialize(err_handler, NULL, OCI_ENV_DEFAULT);

        OCI_Connection* conn = OCI_ConnectionCreate(OTEXT("//xxx.xxx.xxx.xxx/nnnn"), OTEXT("user"), OTEXT("password"), OCI_SESSION_DEFAULT);
        OCI_Statement* stmt = OCI_StatementCreate(conn);

        OCI_ExecuteStmt(stmt, OTEXT("select rowid from table_test")); // can be any table that exists and the user has permission to
        OCI_Resultset *rs = OCI_GetResultset(stmt);
        while (OCI_FetchNext(rs))
        {
            printf("%ls\n", OCI_GetString(rs, 1));
        }

        printf("row fetched %d\n", OCI_GetRowCount(rs));

        OCI_Cleanup();
}

int main(int argc, const char * argv[]) {
    vincent_test();
    return 0;
}`

**Comment by AidyCC** [comment] 2021-10-14 11:57
<img width="1267" alt="Screenshot 2021-10-14 at 12 52 06" src="https://user-images.githubusercontent.com/74263551/137312436-e93f2965-0284-45a1-a09d-2b6ebe3fc776.png">

The memory access exception is at an address 16 bytes into the memory pointed to by the OCIRowid*.  I can't find a definition of the OCIRowid structure, but is it possible that the structure is using 'char' internally and therefore wide characters are causing an overflow?

Of course, doesn't explain why it works on Windows.

**Comment by AidyCC** [comment] 2021-10-18 11:50
Ok, so I've created a stand alone OCI sample to test this.  I used cdemo81.c at the starting point an amended it to test this use case.  The sample uses the standard scott demo schema:-

<img width="1261" alt="Screenshot 2021-10-18 at 12 45 51" src="https://user-images.githubusercontent.com/74263551/137724452-1a89365b-8fb3-4b37-95ce-c26a8466b4d5.png">

In short, it works.  No access viloation.  Can you spot a difference with the code here and what OCILib is doing? 
 The full sample is copied below:-

`#ifdef RCSID
static char *RCSid =
   "$Header: rdbms/demo/cdemo81.c /main/11 2017/09/12 21:21:47 aliu Exp $ ";
#endif /* RCSID */

/* Copyright (c) 1996, 2017, Oracle and/or its affiliates. 
All rights reserved.*/

/*

   NAME
     cdemo81.c - Basic OCI V8 functionality

   DESCRIPTION

 *  An example program which adds new employee
 *  records to the personnel data base.  Checking
 *  is done to insure the integrity of the data base.
 *  The employee numbers are automatically selected using
 *  the current maximum employee number as the start.
 *
 *  The program queries the user for data as follows:
 *
 *  Enter employee name:
 *  Enter employee job:
 *  Enter employee salary:
 *  Enter employee dept:
 *
 *  The program terminates if return key (CR) is entered
 *  when the employee name is requested.
 *
 *  If the record is successfully inserted, the following
 *  is printed:
 *
 *  "ename" added to department "dname" as employee # "empno"

   Demonstrates creating a connection, a session and executing some SQL.
   Also shows the usage of allocating memory for application use which has the
   life time of the handle.

   MODIFIED   (MM/DD/YY)
   aliu        09/11/17 - fix bug 21574212
   gak         02/16/15 - Bug 20364067
   aliu        02/04/14 - fix bug 18181823
   aliu        09/03/13 - XbranchMerge aliu_bug-16007835 from st_rdbms_12.1.0.1
   aliu        01/04/13 - fix bug 16007835 - add an variable for connect string 
                          in OCIServerAttach
   lburgess    04/14/06 - lowercase passwords 
   aliu        04/21/06 - use OCIEnvCreate and exit if it fails 
   mjaeger     07/14/99 - bug 808870: OCCS: convert tabs, no long lines
   dchatter    10/14/98 - add the usage of xtrmemsz and usrmempp
   azhao       06/23/97 - Use OCIBindByPos, OCIBindByName; clean up
   echen       12/17/96 - OCI beautification
   dchatter    07/18/96 - delete spurious header files
   dchatter    07/15/96 - hda is a ub4 array to prevent bus error
   mgianata    06/17/96 - change ociisc() to OCISessionBegin()
   aroy        04/26/96 - change OCITransCommitt -> OCITransCommit
   slari       04/24/96 - use OCITransCommitt
   aroy        02/21/96 - fix bug in get descriptor handle call
   lchidamb    02/20/96 - cdemo81.c converted for v8 OCI
   lchidamb    02/20/96 - Creation

*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <oci.h>

static text *username = (text *) "SCOTT";
static text *password = (text *) "tiger";
  /* this dbname can be changed to point to a remote DB for demo to run with */
static text *dbname   = (text *) "<database>";

/* Define SQL statements to be used in program. */
static text *seldept = (text *)"SELECT rowid FROM dept";


static OCIEnv *envhp = NULL;
static OCIError *errhp = NULL;

static void checkerr(/*_ OCIError *errhp, sword status _*/);
static void free_handles(/*svchp, srvhp, authp, stmthp, stmthp1, stmthp2*/);
static void logout_detach_server(/*svchp, srvhp, authp*/);
static sword finish_demo(/*svchp, srvhp, authp, stmthp, stmthp1, stmthp2 */);
int main(/*_ int argc, char *argv[] _*/);

static sword status;

static boolean logged_on = FALSE;

int main(argc, argv)
int argc;
char *argv[];
{
    OCISession *authp = (OCISession *) 0;
    OCIServer *srvhp = NULL;
    OCISvcCtx *svchp = NULL;
    OCIStmt   *stmthp1= NULL;
    OCIDefine *defnp = (OCIDefine *) 0;
    OCIRowid *rowid = NULL;

    sword errcode = 0;
    ub2 rowid_length = 0;
    OraText    rowidBuffer[19];
    memset(rowidBuffer, 0, 19*sizeof(OraText));

    errcode = OCIEnvCreate((OCIEnv **) &envhp, (ub4) OCI_DEFAULT,
                  (dvoid *) 0, (dvoid * (*)(dvoid *,size_t)) 0,
                  (dvoid * (*)(dvoid *, dvoid *, size_t)) 0,
                  (void (*)(dvoid *, dvoid *)) 0, (size_t) 0, (dvoid **) 0);

    if (errcode != 0) {
    (void) printf("OCIEnvCreate failed with errcode = %d.\n", errcode);
    exit(1);
    }

    (void) OCIHandleAlloc( (dvoid *) envhp, (dvoid **) &errhp, OCI_HTYPE_ERROR,
                   (size_t) 0, (dvoid **) 0);

    /* server contexts */
    (void) OCIHandleAlloc( (dvoid *) envhp, (dvoid **) &srvhp, OCI_HTYPE_SERVER,
                   (size_t) 0, (dvoid **) 0);

    (void) OCIHandleAlloc( (dvoid *) envhp, (dvoid **) &svchp, OCI_HTYPE_SVCCTX,
                   (size_t) 0, (dvoid **) 0);

    checkerr(errhp, OCIServerAttach ( srvhp, errhp, (text *)dbname,
                                    (sb4) strlen((char *)dbname), 0));

    /* set attribute server context in the service context */
    (void) OCIAttrSet( (dvoid *) svchp, OCI_HTYPE_SVCCTX, (dvoid *)srvhp,
                     (ub4) 0, OCI_ATTR_SERVER, (OCIError *) errhp);

    (void) OCIHandleAlloc((dvoid *) envhp, (dvoid **)&authp,
                        (ub4) OCI_HTYPE_SESSION, (size_t) 0, (dvoid **) 0);

    (void) OCIAttrSet((dvoid *) authp, (ub4) OCI_HTYPE_SESSION,
                 (dvoid *) username, (ub4) strlen((char *)username),
                 (ub4) OCI_ATTR_USERNAME, errhp);

    checkerr(errhp, OCIDescriptorAlloc(envhp,(void**)&rowid, OCI_DTYPE_ROWID , (size_t) 0, (dvoid **) 0));

    (void) OCIAttrSet((dvoid *) authp, (ub4) OCI_HTYPE_SESSION,
                 (dvoid *) password, (ub4) strlen((char *)password),
                 (ub4) OCI_ATTR_PASSWORD, errhp);

    checkerr(errhp, OCISessionBegin ( svchp,  errhp, authp, OCI_CRED_RDBMS, (ub4) OCI_DEFAULT));

    (void) OCIAttrSet((dvoid *) svchp, (ub4) OCI_HTYPE_SVCCTX,
                   (dvoid *) authp, (ub4) 0,
                   (ub4) OCI_ATTR_SESSION, errhp);

    logged_on = TRUE;

    checkerr(errhp, OCIHandleAlloc( (dvoid *) envhp, (dvoid **) &stmthp1,
           OCI_HTYPE_STMT, (size_t) 0, (dvoid **) 0));

    checkerr(errhp, OCIStmtPrepare(stmthp1, errhp, seldept,
       (ub4) strlen((char *) seldept),
       (ub4) OCI_NTV_SYNTAX, (ub4) OCI_DEFAULT));

    checkerr(errhp, OCIDefineByPos(stmthp1, &defnp, errhp, 1, (dvoid *) &rowid,
                     (sword) sizeof(sword), SQLT_RDD, (dvoid *) 0, (ub2 *)0,
                     (ub2 *)0, OCI_DEFAULT));

    status = OCIStmtExecute(svchp, stmthp1, errhp, (ub4) 1, (ub4) 0,
                                 (CONST OCISnapshot *) NULL, (OCISnapshot *) NULL, OCI_DEFAULT);

    checkerr(errhp, status);
    OCIRowidToChar(rowid, NULL, &rowid_length, errhp);

    OCIRowidToChar(rowid, rowidBuffer, &rowid_length, errhp);

    printf("Rowid Length = %d\n", rowid_length);
    printf("Rowid = %s\n", rowidBuffer);

    OCIDescriptorFree((void*)rowid, OCI_DTYPE_ROWID);

    finish_demo(svchp, srvhp, authp,0, stmthp1,0);
}


void checkerr(errhp, status)
OCIError *errhp;
sword status;
{
  text errbuf[512];
  sb4 errcode = 0;

  switch (status)
  {
  case OCI_SUCCESS:
    break;
  case OCI_SUCCESS_WITH_INFO:
    (void) printf("Error - OCI_SUCCESS_WITH_INFO\n");
    break;
  case OCI_NEED_DATA:
    (void) printf("Error - OCI_NEED_DATA\n");
    break;
  case OCI_NO_DATA:
    (void) printf("Error - OCI_NODATA\n");
    break;
  case OCI_ERROR:
    (void) OCIErrorGet((dvoid *)errhp, (ub4) 1, (text *) NULL, &errcode,
                        errbuf, (ub4) sizeof(errbuf), OCI_HTYPE_ERROR);
    (void) printf("Error - %.*s\n", 512, errbuf);
    break;
  case OCI_INVALID_HANDLE:
    (void) printf("Error - OCI_INVALID_HANDLE\n");
    break;
  case OCI_STILL_EXECUTING:
    (void) printf("Error - OCI_STILL_EXECUTE\n");
    break;
  case OCI_CONTINUE:
    (void) printf("Error - OCI_CONTINUE\n");
    break;
  default:
    break;
  }
}


/* ----------------------------------------------------------------- */
/*  Free the specified handles                                       */
/* ----------------------------------------------------------------- */
void free_handles(svchp, srvhp, authp, stmthp, stmthp1, stmthp2)
OCISvcCtx *svchp; 
OCIServer *srvhp; 
OCISession *authp; 
OCIStmt *stmthp;
OCIStmt *stmthp1;
OCIStmt *stmthp2;
{
  if (srvhp)
    (void) OCIHandleFree((dvoid *) srvhp, (ub4) OCI_HTYPE_SERVER);
  if (svchp)
    (void) OCIHandleFree((dvoid *) svchp, (ub4) OCI_HTYPE_SVCCTX);
  if (errhp)
    (void) OCIHandleFree((dvoid *) errhp, (ub4) OCI_HTYPE_ERROR);
  if (authp)
    (void) OCIHandleFree((dvoid *) authp, (ub4) OCI_HTYPE_SESSION);
  if (stmthp)
    (void) OCIHandleFree((dvoid *) stmthp, (ub4) OCI_HTYPE_STMT);
  if (stmthp1)
    (void) OCIHandleFree((dvoid *) stmthp1, (ub4) OCI_HTYPE_STMT);
  if (stmthp2)
    (void) OCIHandleFree((dvoid *) stmthp2, (ub4) OCI_HTYPE_STMT);
    
  if (envhp)
    (void) OCIHandleFree((dvoid *) envhp, (ub4) OCI_HTYPE_ENV);

  return;
}

/*-------------------------------------------------------------------*/ 
/* Logout and detach from the server                                 */
/*-------------------------------------------------------------------*/ 
void logout_detach_server(svchp, srvhp, authp)
OCISvcCtx *svchp; 
OCIServer *srvhp; 
OCISession *authp; 
{
  if ((status = OCISessionEnd(svchp, errhp, authp, (ub4) 0)))
  {
    printf("FAILED: OCISessionEnd()\n");
    checkerr(errhp, status);
  }

  if ((status = OCIServerDetach(srvhp, errhp, (ub4) OCI_DEFAULT)))
  {
    printf("FAILED: OCIServerDetach()\n");
    checkerr(errhp, status);
  }

  return;
}

/*---------------------------------------------------------------------*/
/* Finish demo and clean up                                            */
/*---------------------------------------------------------------------*/
sword finish_demo(svchp, srvhp, authp, stmthp, stmthp1, stmthp2)
OCISvcCtx *svchp; 
OCIServer *srvhp; 
OCISession *authp; 
OCIStmt *stmthp;
OCIStmt *stmthp1;
OCIStmt *stmthp2;
{

  if (logged_on)
    logout_detach_server(svchp, srvhp, authp);

  free_handles(svchp, srvhp, authp, stmthp, stmthp1, stmthp2);

  OCITerminate(OCI_DEFAULT);

  return OCI_SUCCESS;
}

/* end of file cdemo81.c */ 

`

**Comment by vrogier** [comment] 2021-10-18 12:45
Hi,

Thanks. It is normal that it works as you're not initializing OCI in UTF16 mode.
When using OCI_CHARSET_WIDE, ocilib passes the flag OCI_UTF16  to OCIEnvCreate() 2nd parameter 'mode'.

Vincent

**Comment by AidyCC** [comment] 2021-10-21 09:00
Ok, thanks.

I'll give that a go.

**Comment by vrogier** [comment] 2021-10-21 09:16
@AidyCC  With the code I have provided, do you encounter the issue, in your environment,  when the macro UTF16 is defined ?

**Comment by AidyCC** [comment] 2021-10-21 09:25
Hi Vincent

I'm not in front of my Mac at the moment.  I will try it later on today.

Thanks,

-Adrian

**Closed** 2022-09-07 20:21 UTC
Labels: wontfix / wontdo, oracle client issue/bug
