### ISSUE TITLE
typeinfo.c: oracle types (objects, pl/sql types) describing

### ISSUE THREAD

**Issue by pvanek** [vrogier/ocilib#146] opened 2018-02-22 10:53 UTC
hi Vincent,

it looks like there is a possibility to use real PL/SQL types from OCI finally - eg. to describe it we can use OCITypeByFullName, etc.

Do you think it's possible to get the same level support for PL/SQL types (records, table of...) like we have for NTY (objects) and collections?

FYI, support for these PL/SQL types is part of ODPI-C already:
https://github.com/oracle/odpi

I'm also able to help a bit with my limited knowledge of OCI, but I'll need your guidance for sure ;)

**Comment by vrogier** [comment] 2018-02-22 15:18
Hi,

Yes, it is in my todo list including describing packages, methods, etc....
Note that it describing PL/SQL records and tables is only available with OCI >= 12cR1.

The big difference with odpi is that odpi support for describing is quit "raw" and not oriented end user API.
To add support for describing anything in OCILIB, I need to extend the OCI_TypeInfo API in a sustainable manner, which requires to take time to design it correctly, and not provide raw structures in a DIY manner as odpi could do.

Supporting describing records and PL/SQL table ONLY does not require OCI_TypeInfo changes and can be done quite easily.
I could do in a version 4.6.0. within an acceptable timeframe.

Regards,

Vincent

**Comment by vrogier** [comment] 2018-02-22 17:57
Hi,

In fact OCILIB alread support PL/SQL records and tables since v4.2 released in 2015 👍 

Here is  the changelog from v4.20 

### New Features:

###### Implemented Oracle 12c extended support for PL/SQL types

```
* Support for  PL/SQL boolean, records and index by tables
* These types can be now used in binding calls
* C API: PL/SQL records can now be used using OCI_Object
* C API: PL/SQL Index by tables can now be used using OCI_Coll
* C API: PL/SQL boolean can be used using boolean C type
* C API: Added OCI_BindBoolean()
* C API: Added OCI_ElemSetBoolean(), OCI_ElemGetBoolean()
* C API: Added OCI_ObjectSetBoolean(), OCI_ObjectGetBoolean()
* C API: OCI_TypeInfoGet() supports now records these PL/SQL types
* C API: Added collection type OCI_COLL_INDEXED_TABLE
* C API: Added data type OCI_CDT_BOOLEAN
* C++ API: PL/SQL records can now be used using ocilib::Object
* C++ API: PL/SQL Index by tables can now be used using ocilib::Collection<T>
* C++ API: PL/SQL boolean can be used using bool C++ type
* C++ API: Added template specializations for supporting PL/SQL boolean using C++ bool in the following calls:
    - ocilib::Statement::Bind()
    - ocilib::Object::Get()
    - ocilib::Object::Set()
* C++ API: Added ocilib::Collection<T> specializations for supporting bool data type
* C++ API: Added ocilib::TypeBoolean
* C++ API: Added ocilib::Collection::IndexedTable
* C++ API: Added internal core class ocilib::BindTypeAdaptor<T1, T2>
```

###### Added Memory usage information

```
* C API: Added OCI_GetAllocatedBytes
* C API: Added OCI_MEM_ORACLE, OCI_MEM_OCILIB and OCI_MEM_ALL
* C++ API: Added ocilib::Environment::GetAllocatedBytes()
* C++ API: Added ocilib::Environment::OracleClientBytes, ocilib::Environment::OcilibBytes, ocilib::Environment::AllBytes
```

###### Added Session Max Cursor information

```
* C API: Added OCI_GetMaxCursors()
* C++ API: Added ocilib::Connection::GetMaxCursors()
```

### Enhancements:

###### C++ API:: Enhanced pre/post statement execution check for binds

```
* Before execution, bind buffers are only updated from host variables if Bind Direction has the ocilib::BindInfo::In flag
* After execution, host variables are only updated from bind buffers if Bind Direction has the ocilib::BindInfo::Out flag
```

### Fixes:

```
* C API: Fixed OCI_GetLastError() that returned NULL after OCI_Initialize() if OCI shared lib cannot be loaded
* C API: Fixed OCI_ColumnGetSQLType() that has its break statements within the switch removed by mistake leading to return "?" in all cases
* C API: Fixed OCI_ElemSetXXX() where XXX is a numeric type
* C API: Fixed OCI_IterFree() when dealing with numbers
* C API: Fixed Memory retention in local OCI objects cache when calling OCI_ObjectFree(): Objects indicator structures were not freed until calling OCI_Cleanup()
* C API: Fixed OCI_ElemSetXXX() for numeric types when element is created using OCI_ElemCreate() instead of being retrieved with OCI_IterGetPrev() or OCI_IterGetNext()
* C API: When OCI_SubscriptionRegister() failed, the input connection was freed leading the caller to hold a dangling pointer to the connection handle
* C API: Fixed comparison call in OCI_TimestampCompare()
* C API: Fixed alignment computation in OCI_GetStruct()
* C API: Fixed alignment computation in OCI_ObjectGetUserStructSize()
* C API: Fixed compilation under compilers that require variable to be declared at the beginning of blocks (example : VS2010)
* C API: Fixed minor internal bugs and issues
* C++ API: ocilib::HandleHolder<T>::Acquire() => Made sure that a smart handle is not allocated if the input C handle is NULL (even if it shall not happen as the C API must raise an error if it cannot return a valid handle)
* C++ API: ocilib::HandleHolder<T>::SmartHandle::~SmartHandle() => the C API handle free function is now called only if the handle is not NULL
* C++ API: Fixed compilation error when using OCI_CHARSET_WIDE
* C++ API: Fixed ocilib::Raw binding when using OCI_CHARSET_WIDE
* C++ API: Fixed ocilib::BindArray::BindArrayObject<Raw, unsigned char>::SetInData()
* C++ API: Fixed binding array of Blobs
* C++ API: Fixed binding array of Raw
```

### Miscellaneous

```
* Doxygen documentation: Added C and C++ data types mappings documentation page
* Removed references to sourceforge.net
* Minor internal code changes to fixing hypothetical issues found by code analysis (CppCheck)
* Fixed some typos and formatting issues
```

**Comment by pvanek** [comment] 2018-02-23 07:27
This is *excellent*! Is there some example/howto how to use it? Or does it work out of the box with "dot access method" (SCHEMA.PACKAGE_NAME.TYPE_NAME)?

**Comment by vrogier** [comment] 2018-02-23 08:30
Hi,

It works out of the box with OCI_TypeInfoGet() using <schema.package.type>
as name and OCI_TIF_TYPE.

You can use records as regular OCI_Object* and table of xxx as regular
OCI_Coll*.

I will add here an example by midday:)

Vincent

**Comment by vrogier** [comment] 2018-02-23 08:57
Here are an example:

SQL script:

```sql
create or replace package test_record as
    type record_t IS RECORD
    (
        value1    NUMBER,
        value2    NUMBER
    );
    type record_table_t is table of record_t index by binary_integer;
    procedure combine_values(list in record_table_t, res out varchar2);
end;
/

create or replace package body test_record as
    procedure combine_values(list in record_table_t, res out varchar2) is 
    begin    
        for i in list.first .. list.last
        loop            
            res := res || (list(i).value1 + list(i).value2) || ' ';
        end loop;      
     end;
end;
/
create or replace package body test_record as
    procedure combine_values(list in record_table_t, res out varchar2) is 
    begin    
        for i in list.first .. list.last
        loop            
            res := res || (list(i).value1 + list(i).value2) || ' ';
        end loop;      
     end;
end;
/
```

OCILIB code:

```c
#include "ocilib.h"

void err_handler(OCI_Error *err)
{
    printf("%s\n", OCI_ErrorGetString(err));
}

int main(void)
{
    OCI_Connection *cn;
    OCI_Statement *st;
    OCI_Coll *cs;
    OCI_Object *rc;
    OCI_Elem *el;
    int i;
    otext res[200] = "";

    OCI_Initialize(err_handler, NULL, OCI_ENV_DEFAULT);
    
    cn = OCI_ConnectionCreate("db", "usr", "pwd", OCI_SESSION_DEFAULT);
    st = OCI_StatementCreate(cn);
    rc = OCI_ObjectCreate(cn, OCI_TypeInfoGet(cn, "usr.test_record.record_t", OCI_TIF_TYPE));
    cs = OCI_CollCreate(OCI_TypeInfoGet(cn, "usr.test_record.record_table_t", OCI_TIF_TYPE));
    el = OCI_ElemCreate(OCI_CollGetTypeInfo(cs));

    for (i = 1; i <= 10; i++)
    {
        OCI_ObjectSetInt(rc, "value1", i);
        OCI_ObjectSetInt(rc, "value2", i+1);
        OCI_ElemSetObject(el, rc);
        OCI_CollAppend(cs, el);
    }

    OCI_ObjectFree(rc);
    OCI_ElemFree(el);

    OCI_Prepare(st, "BEGIN test_record.combine_values(:cs, :res); END;");
    OCI_BindColl(st, ":cs", cs);
    OCI_BindString(st, ":res", res, 200);

    OCI_BindSetDirection(OCI_GetBind(st, 1), OCI_BDM_IN);
    OCI_BindSetDirection(OCI_GetBind(st, 2), OCI_BDM_OUT);

    OCI_Execute(st);
    printf("result is : %s\n", res);

    OCI_StatementFree(st);
    OCI_CollFree(cs);
    OCI_ConnectionFree(cn);
    OCI_Cleanup();

    return EXIT_SUCCESS;
}
```

output is 

```text
result is : 3 5 7 9 11 13 15 17 19 21
```

**Comment by pvanek** [comment] 2018-02-23 10:12
hmm, I'm getting
```
OCI-21602: operation does not support the specified typecode
```
on line
```
OCI_ElemSetObject(el, rc);
```

**Comment by vrogier** [comment] 2018-02-23 10:14
What is your Oracle Version (OCI client, Database Server) ?

**Comment by pvanek** [comment] 2018-02-23 10:17
ocilib: current git snapshot

Server:
```
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
PL/SQL Release 12.2.0.1.0 - Production
"CORE	12.2.0.1.0	Production"
TNS for Linux: Version 12.2.0.1.0 - Production
NLSRTL Version 12.2.0.1.0 - Production
```

client (instant client): 12.2.0.1.0

**Comment by vrogier** [comment] 2018-02-23 10:55
Can you find out what OCI call returns this error ?

**Comment by vrogier** [comment] 2018-02-23 10:55
and can you provide your record definition ?

**Comment by pvanek** [comment] 2018-02-23 11:34
I'm using your example from above: https://github.com/vrogier/ocilib/issues/146#issuecomment-367949037

It fails in
```
    OCI_ELEM_SET_VALUE
    (
        OCI_CDT_OBJECT,
        OCI_Object*,
        OCI_ObjectInit(elem->con, (OCI_Object *) elem->obj, elem->handle, elem->typinf->cols[0].typinf, NULL, -1, TRUE),
        OCI_ObjectAssign((OCI_Object *) elem->obj, value)
    )
```

I think (regarding additiona printf added) it's in macro's OCI_STATUS = func_assign; line.
So it's probably in OCI_ObjectAssign

**Comment by vrogier** [comment] 2018-02-23 11:38
You are using same definition that I've provided or your custom record type ?

**Comment by pvanek** [comment] 2018-02-23 11:38
yours definition

**Comment by vrogier** [comment] 2018-02-23 11:51
I am running 12.2.0.1 on Windows and not have this issue.
Just for being sure, can you add the following to the test code once the connection is created and send it back ?

thansk

    printf("OCI compile     version : %u\n", OCI_VER_MAJ(OCI_GetOCICompileVersion()));
    printf("OCI runtime     version : %u\n\n", OCI_VER_MAJ(OCI_GetOCIRuntimeVersion()));
    printf("Server major    version : %u\n", OCI_GetServerMajorVersion(cn));
    printf("Server minor    version : %u\n", OCI_GetServerMinorVersion(cn));
    printf("Server revision version : %u\n\n", OCI_GetServerRevisionVersion(cn));
    printf("Connection      version : %u\n\n", OCI_GetVersionConnection(cn));

**Comment by pvanek** [comment] 2018-02-23 11:53
```
OCI compile     version : 12
OCI runtime     version : 12

Server major    version : 12
Server minor    version : 2
Server revision version : 0

Connection      version : 1210
```

I run everything on Linux 64 bit

**Comment by vrogier** [comment] 2018-02-23 11:56
Thansks.

I am also running 64bits but I've realised that my version is 12cR1 not 12cR2. I will check if using a 12cR2 client is producing the error.

**Comment by vrogier** [comment] 2018-02-23 12:00
Bingo ! With an instant client 12cR2, i get the same error

`OCI-21602: operation does not support the specified typecode`

Thus it seems to be a breaking change or regression in 12cR2 with OCIObjectCopy holding SQL Record types!

**Comment by vrogier** [comment] 2018-02-23 12:00
For now, you can use an instant client 12cR1 for testing

**Comment by vrogier** [comment] 2018-02-23 13:01
Can you also confirm on side that using a 12cR1 client solve the issue ?
thanks.

**Comment by vrogier** [comment] 2018-02-23 17:07
FIY, the same sample code using non pl/sql record and tables, like using a VARRAY of MyType is working fine with both 12cR1 and R2 client while it  works only with 12cR1 client for PL/SQL records.

I've asked the opdi and nodejs-oracle maintainers (from Oracle) if if could be a bug introduced in 12cR2 client.

I will let you know once I get more information

Regards,

Vincent

**Comment by vrogier** [comment] 2018-02-25 11:04
Hi, 

I've sent them a pure OCI sample application that reproduces the issue and also shows that calling OCIObjectFree() on a pl/SQL record generates the same error code 21602 whatever Oracle client 12c version (R1 or R2), implying maybe possible memory leaks.

I will keep you updated once I get more information.

Regards,

Vincent

**Comment by pvanek** [comment] 2018-02-26 14:25
hi, confirmed - all works with _oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm_ and _oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm_

**Comment by cjbj** [comment] 2018-02-28 20:36
For the record, this is being tracked in Oracle bug 27597199.

**Comment by pvanek** [comment] 2018-03-01 20:14
@cjbj thanks. Is there some "public" link for this issue, please? (SR, whatever) I cannot find it in Metalink...

**Comment by cjbj** [comment] 2018-03-07 02:35
@pvanek I just marked it to be published; sorry there isn't any visible content but you can follow the state.

**Closed** 2018-03-21 08:00 UTC
Labels: question
