### ISSUE TITLE
oracle 9i client connect to 12c database SCROLLABLE Mode get result error

### ISSUE THREAD

**Issue by dadamimi** [vrogier/ocilib#180] opened 2018-10-14 07:38 UTC
hi I have a table "test" values T1 varchar(256) ,T2 varchar(256) ,T3 varchar(256) 
T1,T2 have values, T3 is null.
when I insert 21 rows record into table, call the OCI_FetchLast() and OCI_FetchFirst(),
the 21 row record get the 20 row record result.
But in oracle 11g client and 12c clinet is correct.
I try to insert 22 rows and 20 rows record , the result is correct too.
I try to insert T3 values , the result is correct too.

How can I use SCROLLABLE Mode on oracle 9i client?

Thanks

**Comment by vrogier** [comment] 2018-10-16 06:28
Hi,

Can you provide sample reproducing the issue ?

Best regards,

Vincent

**Comment by dadamimi** [comment] 2018-10-16 07:01
hi:
table : create table TEST(T1 VARCHAR2(256),T2 VARCHAR2(256),T3 VARCHAR2(256))
sql:insert into TEST (T1, T2, T3) values ('11', '11', null);
insert into TEST (T1, T2, T3) values ('22', '22', null);
insert into TEST (T1, T2, T3) values ('33', '33', null);
insert into TEST (T1, T2, T3) values ('44', '44', null);
insert into TEST (T1, T2, T3) values ('55', '55', null);
insert into TEST (T1, T2, T3) values ('66', '66', null);
insert into TEST (T1, T2, T3) values ('77', '77', null);
insert into TEST (T1, T2, T3) values ('88', '88', null);
insert into TEST (T1, T2, T3) values ('99', '99', null);
insert into TEST (T1, T2, T3) values ('100', '100', null);
insert into TEST (T1, T2, T3) values ('101', '101', null);
insert into TEST (T1, T2, T3) values ('102', '102', null);
insert into TEST (T1, T2, T3) values ('103', '103', null);
insert into TEST (T1, T2, T3) values ('104', '104', null);
insert into TEST (T1, T2, T3) values ('105', '105', null);
insert into TEST (T1, T2, T3) values ('106', '106', null);
insert into TEST (T1, T2, T3) values ('107', '107', null);
insert into TEST (T1, T2, T3) values ('108', '108', null);
insert into TEST (T1, T2, T3) values ('109', '109', null);
insert into TEST (T1, T2, T3) values ('110', '110', null);
insert into TEST (T1, T2, T3) values ('111', '111', null);

code:
OCI_Connection *cn;
    OCI_Statement *st;
    OCI_Resultset *rs;
    if (!OCI_Initialize(err_handler, NULL, OCI_ENV_DEFAULT))
    {
        return EXIT_FAILURE;
    }
    cn = OCI_ConnectionCreate("TEST", "test", "test", OCI_SESSION_DEFAULT);
	printf("server %s %i %i %i\n", OCI_GetVersionServer(cn),OCI_GetServerMajorVersion(cn),OCI_GetServerMinorVersion(cn),OCI_GetServerRevisionVersion(cn));
	printf("client  %i \n", OCI_GetVersionConnection(cn));
    st = OCI_StatementCreate(cn);
    OCI_SetFetchMode(st, OCI_SFM_SCROLLABLE);
	OCI_ExecuteStmt(st, "select * from  TEST");
    rs = OCI_GetResultset(st);
    OCI_FetchLast(rs);
	printf("resultset contains %i rows\n", OCI_GetRowCount(rs));
    OCI_FetchFirst(rs);
	OCI_FetchLast(rs);
	printf("resultset contains %i rows\n", OCI_GetRowCount(rs));
    OCI_FetchFirst(rs);

	printf("%s - %s\n", OCI_GetString(rs, 1), OCI_GetString(rs, 2));
    while (OCI_FetchNext(rs))
    {
		printf("%s - %s\n", OCI_GetString(rs, 1), OCI_GetString(rs, 2));
    }
	OCI_FetchSeek(rs, OCI_SFD_ABSOLUTE, 21);
	printf("%s - %s\n", OCI_GetString(rs, 1), OCI_GetString(rs, 2));
    OCI_StatementFree(st);
    OCI_ConnectionFree(cn);
    OCI_Cleanup();
getchar();

Result:
server Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Product
ion
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing opt
ions 12 1 0
client  900
resultset contains 21 rows
resultset contains 21 rows
11 - 11
22 - 22
33 - 33
44 - 44
55 - 55
66 - 66
77 - 77
88 - 88
99 - 99
100 - 100
101 - 101
102 - 102
103 - 103
104 - 104
105 - 105
106 - 106
107 - 107
108 - 108
109 - 109
110 - 110
110 - 110
110 - 110
Press any key to continue

The 21 rows is error.

Thanks.

**Comment by dadamimi** [comment] 2018-10-16 07:02
> Hi,
> 
> Can you provide sample data + code reproducing the issue ?
> 
> Best regards,
> 
> Vincent

hi:
table : create table TEST(T1 VARCHAR2(256),T2 VARCHAR2(256),T3 VARCHAR2(256))
sql:insert into TEST (T1, T2, T3) values ('11', '11', null);
insert into TEST (T1, T2, T3) values ('22', '22', null);
insert into TEST (T1, T2, T3) values ('33', '33', null);
insert into TEST (T1, T2, T3) values ('44', '44', null);
insert into TEST (T1, T2, T3) values ('55', '55', null);
insert into TEST (T1, T2, T3) values ('66', '66', null);
insert into TEST (T1, T2, T3) values ('77', '77', null);
insert into TEST (T1, T2, T3) values ('88', '88', null);
insert into TEST (T1, T2, T3) values ('99', '99', null);
insert into TEST (T1, T2, T3) values ('100', '100', null);
insert into TEST (T1, T2, T3) values ('101', '101', null);
insert into TEST (T1, T2, T3) values ('102', '102', null);
insert into TEST (T1, T2, T3) values ('103', '103', null);
insert into TEST (T1, T2, T3) values ('104', '104', null);
insert into TEST (T1, T2, T3) values ('105', '105', null);
insert into TEST (T1, T2, T3) values ('106', '106', null);
insert into TEST (T1, T2, T3) values ('107', '107', null);
insert into TEST (T1, T2, T3) values ('108', '108', null);
insert into TEST (T1, T2, T3) values ('109', '109', null);
insert into TEST (T1, T2, T3) values ('110', '110', null);
insert into TEST (T1, T2, T3) values ('111', '111', null);

code:
OCI_Connection *cn;
OCI_Statement *st;
OCI_Resultset *rs;
if (!OCI_Initialize(err_handler, NULL, OCI_ENV_DEFAULT))
{
return EXIT_FAILURE;
}
cn = OCI_ConnectionCreate("TEST", "test", "test", OCI_SESSION_DEFAULT);
printf("server %s %i %i %i\n", OCI_GetVersionServer(cn),OCI_GetServerMajorVersion(cn),OCI_GetServerMinorVersion(cn),OCI_GetServerRevisionVersion(cn));
printf("client %i \n", OCI_GetVersionConnection(cn));
st = OCI_StatementCreate(cn);
OCI_SetFetchMode(st, OCI_SFM_SCROLLABLE);
OCI_ExecuteStmt(st, "select * from TEST");
rs = OCI_GetResultset(st);
OCI_FetchLast(rs);
printf("resultset contains %i rows\n", OCI_GetRowCount(rs));
OCI_FetchFirst(rs);
OCI_FetchLast(rs);
printf("resultset contains %i rows\n", OCI_GetRowCount(rs));
OCI_FetchFirst(rs);

printf("%s - %s\n", OCI_GetString(rs, 1), OCI_GetString(rs, 2));
while (OCI_FetchNext(rs))
{
	printf("%s - %s\n", OCI_GetString(rs, 1), OCI_GetString(rs, 2));
}
OCI_FetchSeek(rs, OCI_SFD_ABSOLUTE, 21);
printf("%s - %s\n", OCI_GetString(rs, 1), OCI_GetString(rs, 2));
OCI_StatementFree(st);
OCI_ConnectionFree(cn);
OCI_Cleanup();
getchar();

Result:
server Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Product
ion
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing opt
ions 12 1 0
client 900
resultset contains 21 rows
resultset contains 21 rows
11 - 11
22 - 22
33 - 33
44 - 44
55 - 55
66 - 66
77 - 77
88 - 88
99 - 99
100 - 100
101 - 101
102 - 102
103 - 103
104 - 104
105 - 105
106 - 106
107 - 107
108 - 108
109 - 109
110 - 110
110 - 110
110 - 110
Press any key to continue

The 21 rows is error.

Thanks.

**Comment by vrogier** [comment] 2018-10-17 17:01
Hi,

If I understand it correctly, same code runs fine with oracle client 10g
and 11g but fails with client 9i with same 12c server? Seems to be an issue
with your exact 9i version.

I do not have access at the moment  to 9i client.
If I send you a modified resultset.c file with added traces, could you
recompile ocilib, run your test and send me back the output?

Regards,

Vincent

**Comment by dadamimi** [comment] 2018-10-18 01:28
> Hi, If I understand it correctly, same code runs fine with oracle client 10g and 11g but fails with client 9i with same 12c server? Seems to be an issue with your exact 9i version. I do not have access at the moment to 9i client. If I send you a modified resultset.c file with added traces, could you recompile ocilib, run your test and send me back the output? Regards, Vincent

Hi,
    Sure, how I can get your modified resultset.c file ?
    git or mail to me? my email is iChtholly@gmail.com
    I think the error in the OCI_FetchFirst() or OCI_FetchLast() interface.
    If I not call the OCI_FetchFirst() and OCI_FetchLast() , while (OCI_FetchNext(rs)) print result correctly.

Thanks.

**Comment by dadamimi** [comment] 2018-10-18 04:40
> Hi, If I understand it correctly, same code runs fine with oracle client 10g and 11g but fails with client 9i with same 12c server? Seems to be an issue with your exact 9i version. I do not have access at the moment to 9i client. If I send you a modified resultset.c file with added traces, could you recompile ocilib, run your test and send me back the output? Regards, Vincent

Hi,
    I try to change ociliba.dll version, I founnd 3.8.1 works correctly but error in 3.9.4.
    I compare the resultset.c ,OCI_FetchFirst() and OCI_FetchLast() interface add a line 
    'OCI_CHECK_STMT_STATUS(rs->stmt, OCI_STMT_EXECUTED, FALSE);'
    Now, I have not environment built  4.5.2 ocilib.dll. I want to try remove 
    'OCI_CHECK_STMT_STATUS()' and rebuilt dll.
    
Thanks.

**Comment by vrogier** [comment] 2018-10-18 07:45
Hi,

Here is a 32bit / ANSI build of ocilib DLL with extended traces (std output) : [ociliba.zip](https://github.com/vrogier/ocilib/files/2490710/ociliba.zip)

can you run your sample with a  9i client and with a 10/11g client ?
Then send me back both results and I will be able to investigate the issue.
Thanks.

Vincent

**Comment by dadamimi** [comment] 2018-10-18 08:09
> Hi,
> 
> Here is a 32bit / ANSI build of ocilib DLL with extended traces (std output) : [ociliba.zip](https://github.com/vrogier/ocilib/files/2490710/ociliba.zip)
> 
> can you run your sample with a 9i client and with a 10/11g client ?
> Then send me back both results and I will be able to investigate the issue.
> Thanks.
> 
> Vincent

Hi,
    Program execution crash when call OCI_ConnectionCreate interface.
    Which hard disk path  you write  traces logs ?
Thanks.

**Comment by vrogier** [comment] 2018-10-18 08:30
Here is  new dll (previous one was based on unstable dev branch). 
this one is a 4.5.2 with just traces added.
[ociliba_4.5.2_modified.zip](https://github.com/vrogier/ocilib/files/2490923/ociliba_4.5.2_modified.zip)

**Comment by vrogier** [comment] 2018-10-18 08:32
traces are just output on the standard output.

**Comment by dadamimi** [comment] 2018-10-18 08:46
> Here is new dll (previous one was based on unstable dev branch).
> this one is a 4.5.2 with just traces added.
> [ociliba_4.5.2_modified.zip](https://github.com/vrogier/ocilib/files/2490923/ociliba_4.5.2_modified.zip)

Hi,
Here is 9i 11g 12c Client output logs.
Thanks.
[9i.log](https://github.com/vrogier/ocilib/files/2490978/9i.log)
[11g.log](https://github.com/vrogier/ocilib/files/2490979/11g.log)
[12c.log](https://github.com/vrogier/ocilib/files/2490980/12c.log)

**Comment by vrogier** [comment] 2018-10-18 09:03
Traces show exactly same executed code, same resultset internal member values and same oracle client call result codes between 9i and other versions !
Seems that only the content of the buffers changes.
Weird.
I will add other traces to OCI_GetString() .
What is your exact Oracle 9i client version ?

**Comment by dadamimi** [comment] 2018-10-18 09:10
> Traces show exactly same executed code, same resultset internal member values and same oracle client call result codes between 9i and other versions !
> Seems that only the content of the buffers changes.
> Weird.
> I will add other traces to OCI_GetString() .
> What is your exact Oracle 9i client version ?

Hi,
e....9.0.1.0.1, maybe. sqlplus show this version.
sqlplus and pl/sql excute result correctly.

**Comment by vrogier** [comment] 2018-10-18 09:20
If you set OCI_SetFetchSize(st, 1) prior executg the statement, what is the result with 9i ?

**Comment by vrogier** [comment] 2018-10-18 09:36
what is the error  ?

Here the a new dll with more traces in OCI_GetString() that shows the value of internal buffers. 
[ociliba_4.5.2_modified_2.zip](https://github.com/vrogier/ocilib/files/2491223/ociliba_4.5.2_modified_2.zip)

Can you run again the 9i test and send me back the outout ?

**Comment by dadamimi** [comment] 2018-10-18 09:57
> what is the error ?
> 
> Here the a new dll with more traces in OCI_GetString() that shows the value of internal buffers.
> [ociliba_4.5.2_modified_2.zip](https://github.com/vrogier/ocilib/files/2491223/ociliba_4.5.2_modified_2.zip)
> 
> Can you run again the 9i test and send me back the outout ?

Hi,
    error is the same with 9i client output logs,I mean. I also try to use OCI_GetString2, the same error.
    Here is the new logs.
Thanks.
   
[9i_2.log](https://github.com/vrogier/ocilib/files/2491312/9i_2.log)
[12c_2.log](https://github.com/vrogier/ocilib/files/2491313/12c_2.log)

**Comment by vrogier** [comment] 2018-10-18 12:29
Hi,

I might have spotted a possible difference of behavior between 9i and other versions.
Here is a new modified dll:[ociliba_4.5.2_modified_3.zip](https://github.com/vrogier/ocilib/files/2491866/ociliba_4.5.2_modified_3.zip)

Can you test it with your 9i client and send me the logs ?
Thanks.

vincent

**Comment by dadamimi** [comment] 2018-10-18 14:09
> Hi,
> 
> I might have spotted a possible difference of behavior between 9i and other versions.
> Here is a new modified dll:[ociliba_4.5.2_modified_3.zip](https://github.com/vrogier/ocilib/files/2491866/ociliba_4.5.2_modified_3.zip)
> 
> Can you test it with your 9i client and send me the logs ?
> Thanks.
> 
> vincent

Hi,
There is a little different from 9i_2.log. 
'......FetchData::enter'=> mode=2 offset=1
9i_2.log  offset=0
9i_3.log  offset=1
Thanks.
[9i_3.log](https://github.com/vrogier/ocilib/files/2492193/9i_3.log)

**Comment by dadamimi** [comment] 2018-10-18 14:29
> This difference is wanted. I hoped that it would make a difference.
> Thus, from my point of view, it is an Oracle 9.0.1.0 client issue.
> I will try to reach some people from Oracle to see if they aware of such issue.

Hi,
But ocilib.dll version <= 3.8.1, Oracle 9.0.1.0 client works correctly..........

**Comment by vrogier** [comment] 2018-10-18 14:50
Here is a ocilib dll 3.8.1 modified with same traces : [ociliba-3..8.1-Modified.zip](https://github.com/vrogier/ocilib/files/2492364/ociliba-3.8.1-Modified.zip)

Can you test and post back generated traces ?

thanks

**Comment by dadamimi** [comment] 2018-10-18 14:54
> Here is a ocilib dll 3.8.1 modified with same traces : [ociliba-3..8.1-Modified.zip](https://github.com/vrogier/ocilib/files/2492364/ociliba-3.8.1-Modified.zip)
> 
> Can you test and post back generated traces ?
> 
> thanks

Hi,
Here is the log.
[9i_3.8.1.log](https://github.com/vrogier/ocilib/files/2492384/9i_3.8.1.log)

**Comment by vrogier** [comment] 2018-10-18 21:04
I lost my Debian appliance where I was keeping old oracle 8i and 9i clients.
Thus I cannot test nor debug with a 9.0 client.
Instead I have been comparing 3.8.1 and 3.9.4 code bases as according to your tests it works for 9i with 3.8.1 and fails with version > 3.8.1.
Basically, there is no particular change in the fetch logic.
There is only 1 change in the 3.9.0 release that could theoretically have an impact (in that case, it would be an Oracle bug and would explain why not reproduced with client 10g and above). 

From the changelog:
`    - Fixed OCI_SetPrefetchSize(), OCI_SetPrefetchMemory() : the given value was not really passed to Oracle`

Starting with 3.9.0, every time a statement is prepared, we set on the statement handle the either the default value (20) either the one assigned to the statement. Prior to 3.9.0 it was not set.

Here is another dll based on 3.8.1 with the change mentioned above reverted.
[ociliba-3..8.1-Modified_PreFetch.zip](https://github.com/vrogier/ocilib/files/2493608/ociliba-3.8.1-Modified_PreFetch.zip)

Can you test and post back generated traces ?

**Comment by dadamimi** [comment] 2018-10-19 01:38
> I lost my Debian appliance where I was keeping old oracle 8i and 9i clients.
> Thus I cannot test nor debug with a 9.0 client.
> Instead I have been comparing 3.8.1 and 3.9.4 code bases as according to your tests it works for 9i with 3.8.1 and fails with version > 3.8.1.
> Basically, there is no particular change in the fetch logic.
> There is only 1 change in the 3.9.0 release that could theoretically have an impact (in that case, it would be an Oracle bug and would explain why not reproduced with client 10g and above).
> 
> From the changelog:
> `- Fixed OCI_SetPrefetchSize(), OCI_SetPrefetchMemory() : the given value was not really passed to Oracle`
> 
> Starting with 3.9.0, every time a statement is prepared, we set on the statement handle the either the default value (20) either the one assigned to the statement. Prior to 3.9.0 it was not set.
> 
> Here is another dll based on 3.8.1 with the change mentioned above reverted.
> [ociliba-3..8.1-Modified_PreFetch.zip](https://github.com/vrogier/ocilib/files/2493608/ociliba-3.8.1-Modified_PreFetch.zip)
> 
> Can you test and post back generated traces ?

Hi,
Here is the logs.
Thanks.
[9i_PreFetch.log](https://github.com/vrogier/ocilib/files/2494109/9i_PreFetch.log)
[11g_PreFetch.log](https://github.com/vrogier/ocilib/files/2494110/11g_PreFetch.log)

**Comment by dadamimi** [comment] 2018-10-19 06:09
> Bingo! The issue is reproduced with the modified 3.8.1 version. It means that the issue happens only if we use scrollable cursors and we set the number of prefetch rows and only with oracle 9i client. Take the lastest ocilib release 4.5.2 and oracle 9i client. In your code, just before executing the statement, add OCI_SetPrefetchSize(state, 0). The issue shouldn't be reproduced. Thus, this is an oracle bug that had been fixed in 9.2 or 10gR1. Vincent

Hi,
Yes, you are right.  
I try to add OCI_SetPrefetchSize(state, 0) before OCI_ExecuteStmt sql , the result is correctly.
It works correctly on 9i, 11g, 12c oracle client.
Can you tell me why you add  OCI_SetPrefetchSize in ocilib.dll at version >= 3.9 ?
And Do you fix this bug in next version?

**Comment by vrogier** [comment] 2018-10-19 06:39
Can you tell me why you add OCI_SetPrefetchSize in ocilib.dll at version >=
3.9 ?


I did not add it in 3.9.0. I fixed it.
When a statement was prepared, prior to execution, OCI_SetPrefetchSize()
was already called internally with default value. But a bug in ocilib made
the value passed to oracle being zero instead.
Thus, the change in 3.9.0 was to set real value.

And Do you fix this bug in next version?


Hum. This is an oracle bug that has been fixed since by oracle (at least
10gR1).
It affects unsupported clients (9iR1 confirned and possibly 9iR2 ??).

Shall I provide a workaround for an unsupported client version released 17
years ago and being 8 Oracle major version behind?

Why not... But what would be the fix ? Disabling prefetching for 9iR1? What
about 9iR2?

And there also a workaround that works.
I could just document it in the documentation.

If you have a 9iR2 client to test with or even better access to oracle
support (I do not have access anymore) to find the bug id and confirmation
of being fixed in a given version, I might see to disable prefetching for
scrollable cursors for impacted versions.

Regards,

Vincent

**Comment by vrogier** [comment] 2018-10-25 14:16
I've pushed a workaround onto branch develop-4.6.0

**Closed by vrogier** 2018-10-25 14:16 UTC
Labels: oracle client issue/bug
