### ISSUE TITLE
OciLib 4.6.2  ocilib_tests (in Test folder) fails in TestLob Suite

### ISSUE THREAD

**Issue by alexsmcse** [vrogier/ocilib#208] opened 2019-05-16 21:42 UTC
Hi,
ocilib_test.sln  TestLob AssignNotEmpty and Truncate test cases fail when run in OCI_CHARSET_ASCII mode as VS2019 x64 application, Oracle Database 12c Enterprise Edition Release 12.1.0.1.0 - 64 bit

Can you please check your code?
Thank you.

**Comment by alexsmcse** [comment] 2019-05-20 18:44
Sorry, was caused by compiler Character Code setting mismatch - Unicode vs Multi-Byte between the compiled library and the test code.

**Comment by vrogier** [comment] 2019-07-22 20:02
Hi,

Can you provide more information about the failure ?
I cannot reproduce with VS2019 16.1.6 + latest  version of gtest + various client (11, 12, 18) against a 18c db.

Regards,

Vincent

**Comment by vrogier** [comment] 2019-10-30 19:35
Hi,

Have you tried v4.6.3 branch?
If is now merged in master branch.
I would need your feedback before publishing 4.6.3 release.
Thanks.

Vincent

**Comment by alexsmcse** [comment] 2019-10-30 23:05
Hi Vincent,

Unfortunately, I still can't get any stable deterministic behavior of the library under Gtest (VS 2019).
Whatever I tried still could not yield any stable, trustful results - I finally gave up any further tries.
Vincent, I do believe it might seem a bit odd to you, but I would rather have a sort of
shared debug session with you (you choose whatever desktop sharing tool you find appropriate to you)
to have it all done once and definite.
Otherwise I'm afraid I can't go on providing any decent input to your development / be determined in giving the GO sign.
Thanks for your reply, as I was about writing this message on my own quite soon.
Hope to hearing from you.

Regards,
Alex


________________________________
Von: Vincent Rogier <notifications@github.com>
Gesendet: Mittwoch, 30. Oktober 2019 19:35
An: vrogier/ocilib <ocilib@noreply.github.com>
Cc: alexsmcse <alexsprivat@hotmail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [vrogier/ocilib] OciLib 4.6.2 ocilib_tests (in Test folder) fails in TestLob Suite (#208)


Hi,

Have you tried v4.6.3 branch?
If is now merged in master branch.
I would need your feedback before publishing 4.6.3 release.
Thanks.

Vincent

**Comment by vrogier** [comment] 2021-09-06 18:23
Closing the issue as cannot reproduce and no news for a while.

@alexsmcse in case the issue is still relevant to you with latest codebase, please, contact me.

**Closed** 2021-09-06 18:24 UTC
Labels: invalid, wontfix / wontdo, discarded (no news from op), C API, Unit testing
