### ISSUE TITLE
Hexa raw

### ISSUE THREAD

**Issue by nedcurzon** [vrogier/ocilib#106] opened 2017-09-21 15:27 UTC
Hi
I'm starting to using OCILIB. I'm using:
	ocilib-4.3.3-windows
	oraocci12d.lib

I think is great and try to put it in the company but I find a little issue.
I'm retrieving hexa information from a table with a raw column: 
			  JRNL_BODY       RAW(3650)

                (in sqlplus:)
		SELECT  j.jrnl_body FROM USR_JRNAL J
			0000083B000003E90000001000000456000009EF000003E8000000100000006E000008......
			len: 7300
			
	If you need the dump is here: 
		SELECT dump(j.jrnl_body) FROM USR_JRNAL J
			Typ=23 Len=3650: 0,0,8,59,0,0,3,233,0,0,0,16,0,0,4,86,0,0,9,239,0,0,3,232,0,0,0,16,0,0,0,110,0,0,8,56,0,0,3,233...
			
	
	This is the code: 
	
		Environment::Initialize();
		Connection con("DB", "USR", "xx");

		std::string sql = "SELECT j.jrnl_body FROM USR_JRNAL J";

		Statement st(con);
		st.SetLongMode(Statement::LongExplicit);
		st.Execute(sql);

		Resultset rs1 = st.GetResultset();
		while (rs1++)		{
			  Raw raw = rs1.Get<Raw>(1); // raw is null
			  //do something ...
		}
	I can't retrieve as string because of \0  
            auxStr = rs1.Get<ostring>(1);
         and generates a signal 11 in 
              inline ostring Resultset::Get<ostring>(unsigned int index) const
              {
                     return MakeString(Check(OCI_GetString(*this, index)));
             }

	The cuestion is: the raw object only sees the binary data, not in HEXA. 
	And de binary has \0 so the Raw vector is empty. 
	I even try do the same with a package, but I've got the same result 	
		//rc and rb are sys_refcursors 
		std::string sql = "BEGIN PKG_XXX.SP_GET_TDES_RF_SEP (:rc, :rb);end;";
						  
		Statement st(con);
		Statement rc(con);
		Statement rb(con);
		
		st.Prepare(sql);
		st.Bind(":rc", rc, BindInfo::Out);
		st.Bind(":rb", rb, BindInfo::Out);
		
		st.SetLongMode(Statement::LongExplicit);
		rb.SetLongMode(Statement::LongExplicit);
		st.ExecutePrepared();
		Resultset rs = rc.GetResultset();
		Resultset rv = rb.GetResultset();
		
		....
			Raw raw = rv.Get<Raw>(1); // raw is null

	I need to be able to see the data as I see in a sqlplus or even with plain oci functions in HEXA: 
		rs = stmt->executeQuery();
		auxStr = rs->getString(1); // "0000083B000003E90000001000..."
	
	
	I saw many convertions types in the code. Perhaps one of them is making the convertion for me or perhaps I'm picking the incorrect data (Raw). I don't know.  Can you help me with this issue?

Thanks in advance

**Comment by vrogier** [comment] 2017-09-22 22:02
Hi,

First, you are not dealing with LONG columns, thus you shall not set the LongMode property of the statement.
OCILIB Raw type is just a vector<unsigned char>, thus it cannot be "null" as you've mentioning.
It is not related to LONG data type.

I cannot reproduce your issue.
I may not have properly understood your issue .

I've created a quick test case and it gives the expected output

Sql:

```sql
    create table test_raw ( value raw(2000) );
    insert into test_raw values (utl_raw.concat(utl_raw.cast_from_number(1234),hextoraw('0000'), utl_raw.cast_from_number(56789))) ;
```


code:

```c++
    Statement st(con);
    st.Execute("select * from test_raw");
    Resultset rs = st.GetResultset();
    while (rs++)
    {
        std::cout << "Raw value is: ";

        for (auto c : rs.Get<Raw>(1))
        {
            std::cout << std::to_string(c);
        }

        std::cout << std::endl;
    }
```
        
        
output is :
        

`    Raw value is: 19413350019566890`

And compared to sql dump command:

```
SQL> select dump(value) from test_raw;

DUMP(VALUE)
--------------------------------------------------------------------------------
Typ=23 Len=9: 194,13,35,0,0,195,6,68,90



```

**Comment by nedcurzon** [comment] 2017-10-20 22:13
Hi, I'm sorry not to answer before but I've had some problems and I can't
open this account.
Thank you very much for your replay. I'm in a new job now and I trying to
implement your library because I thing is a very good work. Really.
I'm going to reproduce this behavior in my new job and I'll send you
feedback. But in the meantime I can say that I've switch to the C api and
I've read the hexa values. And if I switch to the C++ api I've only saw the
binary data.
I'm going to make a new example and let you know

thank you very much.

regards

**Comment by vrogier** [comment] 2017-11-06 17:46
Hi,

Any news / update?

Regards,

Vincent

**Comment by vrogier** [comment] 2017-11-28 20:17
Hi,

Any news / update? In case of no update from you, I will close this issue.

Regards,

Vincent

**Closed** 2018-01-13 12:14 UTC
Labels: discarded (no news from op), help wanted
